using System.IO;
using FluentAssertions;
using MTTextClient.Core;
using MTTextClient.Tests.Infrastructure;
using Newtonsoft.Json.Linq;
using Xunit;
using ReadmeGen = MTTextClient.Tools.RegistryReadmeGenerator.Program;

namespace MTTextClient.Tests.Static;

/// <summary>
/// Stage 0.3 / OV-2 — the README's autogenerated tool table must stay in
/// lockstep with <see cref="ToolRegistry.AllTools"/>. The table lives between
/// the BEGIN / END markers managed by <c>tools/RegistryReadmeGenerator</c>.
/// This test re-runs the generator's <c>Render</c> method in-process,
/// asserts the rendered table appears verbatim in README.md, and asserts
/// every registry tool name is listed.
///
/// To regenerate after an intentional change to descriptions / required args:
///   <c>dotnet run --project tools/RegistryReadmeGenerator -c Release</c>
/// and commit the updated README.md.
/// </summary>
[Collection(McpCollection.Name)]
[Trait("Category", TraitCategories.Static)]
public sealed class ReadmeParityTests
{
    [Fact]
    public void ReadmeAutogeneratedSection_IsByteEqualToCurrentRegistryRender()
    {
        string path = ResolveReadmePath();
        File.Exists(path).Should().BeTrue(because: "README.md must exist at repo root");

        string readme = File.ReadAllText(path);
        string rendered = ReadmeGen.Render(ToolRegistry.AllTools());

        readme.Should().Contain(rendered,
            because: "the autogenerated registry table must appear verbatim " +
                     "in README.md between the BEGIN/END markers. If this " +
                     "fails after an intentional change to a tool description " +
                     "or required args, regenerate via: " +
                     "`dotnet run --project tools/RegistryReadmeGenerator -c Release` " +
                     "and commit the updated README.md.");
    }

    [Fact]
    public void Readme_ContainsEveryRegistryToolName()
    {
        string readme = File.ReadAllText(ResolveReadmePath());

        var missing = new System.Collections.Generic.List<string>();
        foreach (var tool in ToolRegistry.AllTools())
        {
            string name = tool["name"]?.Value<string>() ?? "";
            if (string.IsNullOrEmpty(name)) continue;

            // The autogenerated section renders each name as `mt_xxx` (backticks).
            // We look for that exact form to avoid matching prose mentions.
            string needle = "`" + name + "`";
            if (!readme.Contains(needle, System.StringComparison.Ordinal))
                missing.Add(name);
        }

        missing.Should().BeEmpty(
            because: "every registry tool must be listed in the README's tool table. " +
                     "Missing: " + string.Join(", ", missing));
    }

    [Fact]
    public void ReadmeMarkers_AreBothPresent()
    {
        string readme = File.ReadAllText(ResolveReadmePath());
        readme.Should().Contain(ReadmeGen.BeginMarker, because: "the BEGIN marker bounds the autogenerated table");
        readme.Should().Contain(ReadmeGen.EndMarker,   because: "the END marker bounds the autogenerated table");
    }

    private static string ResolveReadmePath() => Path.Combine(RepoPaths.Root, "README.md");
}
