using System;
using System.IO;
using System.Linq;
using System.Text;
using MTTextClient.Core;
using Newtonsoft.Json.Linq;

namespace MTTextClient.Tools.RegistryReadmeGenerator;

/// <summary>
/// Renders an authoritative tool-table from <see cref="ToolRegistry.AllTools"/>
/// and splices it into README.md between the BEGIN / END markers defined by
/// <see cref="BeginMarker"/> and <see cref="EndMarker"/>.
///
/// CLI:
///   dotnet run --project tools/RegistryReadmeGenerator -- [--check]
///
/// Without --check: rewrites README.md in-place. With --check: prints to
/// stdout what the README would look like AND compares the rendered table
/// against the in-file section between the markers; exits 1 if drift.
///
/// The Static <c>ReadmeParityTests</c> calls <see cref="Render"/> directly
/// in-process and asserts the in-file table is byte-equal; the CLI binary
/// is a convenience wrapper around the same rendering function.
/// </summary>
public static class Program
{
    public const string BeginMarker = "<!-- BEGIN AUTOGENERATED REGISTRY TABLE -->";
    public const string EndMarker   = "<!-- END AUTOGENERATED REGISTRY TABLE -->";

    public static int Main(string[] args)
    {
        bool check = args.Contains("--check");
        string readmePath = FindReadme();
        string oldReadme = File.ReadAllText(readmePath);
        string rendered = Render(ToolRegistry.AllTools());
        string newReadme = SpliceBetweenMarkers(oldReadme, rendered);

        if (check)
        {
            bool drifted = newReadme != oldReadme;
            if (drifted)
            {
                Console.Error.WriteLine("[RegistryReadmeGenerator] README.md drift detected. Re-run without --check to regenerate.");
                return 1;
            }
            Console.WriteLine("[RegistryReadmeGenerator] README.md is in sync with the registry.");
            return 0;
        }

        if (newReadme != oldReadme)
        {
            File.WriteAllText(readmePath, newReadme);
            Console.WriteLine($"[RegistryReadmeGenerator] Wrote {readmePath} ({ToolRegistry.AllTools().Count()} tools).");
        }
        else
        {
            Console.WriteLine("[RegistryReadmeGenerator] No changes — README already in sync.");
        }
        return 0;
    }

    /// <summary>
    /// Render the registry as a deterministic markdown table. Each row:
    ///   | `tool_name` | description (single-line) | `required_args` | confirm? |
    /// Tool order matches <see cref="ToolRegistry.AllTools"/> enumeration order,
    /// which itself matches the locked baseline's tool order — so any
    /// reordering inside the registry surfaces immediately as a diff here.
    /// </summary>
    public static string Render(System.Collections.Generic.IEnumerable<JObject> tools)
    {
        var sb = new StringBuilder();
        sb.AppendLine(BeginMarker);
        sb.AppendLine();
        sb.AppendLine("> Auto-generated from `Core/ToolRegistry.cs` by `tools/RegistryReadmeGenerator`. Do not edit by hand — re-run the generator. Static tests fail if this table drifts from the registry.");
        sb.AppendLine();
        sb.AppendLine("| Tool | Description | Required args | Confirm |");
        sb.AppendLine("|------|-------------|---------------|---------|");

        int count = 0;
        foreach (var t in tools)
        {
            string name = t["name"]?.Value<string>() ?? "";
            string desc = (t["description"]?.Value<string>() ?? "")
                .Replace("\r", "")
                .Replace("\n", " ")
                .Replace("|", "\\|")
                .Trim();
            var schema = t["inputSchema"] as JObject;
            string requiredCsv = "—";
            string confirmCell = "—";
            if (schema?["required"] is JArray req)
            {
                var names = req.Select(r => r.Value<string>() ?? "")
                                .Where(s => !string.IsNullOrEmpty(s))
                                .ToList();
                if (names.Count > 0)
                    requiredCsv = string.Join(", ", names.Select(n => $"`{n}`"));
                if (names.Contains("confirm", StringComparer.Ordinal))
                    confirmCell = "✓";
            }
            sb.AppendLine($"| `{name}` | {desc} | {requiredCsv} | {confirmCell} |");
            count++;
        }

        sb.AppendLine();
        sb.AppendLine($"_Total: {count} tools._");
        sb.AppendLine();
        sb.Append(EndMarker);
        return sb.ToString();
    }

    /// <summary>
    /// Replace whatever is between the BEGIN and END markers with the rendered
    /// table. If the markers are missing, append the table at the end of the
    /// document so the next run is idempotent.
    /// </summary>
    private static string SpliceBetweenMarkers(string readme, string rendered)
    {
        int beginIdx = readme.IndexOf(BeginMarker, StringComparison.Ordinal);
        int endIdx   = readme.IndexOf(EndMarker, StringComparison.Ordinal);
        if (beginIdx < 0 || endIdx < 0 || endIdx < beginIdx)
        {
            // No markers yet: append. Idempotent on the next run.
            string trimmed = readme.TrimEnd('\r', '\n');
            return trimmed + "\n\n" + rendered + "\n";
        }
        int afterEnd = endIdx + EndMarker.Length;
        return readme.Substring(0, beginIdx) + rendered + readme.Substring(afterEnd);
    }

    private static string FindReadme()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            string candidate = Path.Combine(dir.FullName, "README.md");
            if (File.Exists(candidate)) return candidate;
            // Stop walking when we leave the repo (no MTTextClient.csproj ancestor).
            if (!File.Exists(Path.Combine(dir.FullName, "MTTextClient.csproj")) && dir.Parent is null)
                break;
            dir = dir.Parent;
        }
        throw new FileNotFoundException("README.md not found in any ancestor of " + AppContext.BaseDirectory);
    }
}
