<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MTTextClient.Tools.RegistryReadmeGenerator</RootNamespace>
    <AssemblyName>RegistryReadmeGenerator</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MTTextClient.csproj" />
  </ItemGroup>

</Project>
